#!/usr/bin/env bash

sudo apt-get install ninja-build gettext cmake curl build-essential git

cd ~
git clone https://github.com/neovim/neovim
cd neovim
make CMAKE_BUILD_TYPE=Release
sudo make install
